### ISSUE TITLE
Reindexing failing in Ruby

### ISSUE THREAD

**Issue by jtoliver** [wizza-smile/SublimeCodeIntel3#5]
I get some autocompletions, but not all. I'm also seeing a bunch of these in my log.
```
Traceback (most recent call last):
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/citadel.py", line 292, in scan
    scan_tree = cile_driver.scan_purelang(self)
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/lang_ruby.py", line 1636, in scan_purelang
    tree = rubycile.scan_purelang(buf.accessor.text, buf.path)
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/rubycile.py", line 287, in scan_purelang
    "Ruby", "Ruby")
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/parser_cix.py", line 227, in produce_elementTree_cix
    produce_elementTree_contents_cix(parse_tree, module_cix_node)
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/parser_cix.py", line 237, in produce_elementTree_contents_cix
    visit_children_get_cix(parse_tree, cix_node)
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/parser_cix.py", line 215, in visit_children_get_cix
    cb_etree_hash[c.class_name](c, cix_node)
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/parser_cix.py", line 206, in module_etree_cix
    common_module_class_cix(parse_tree_node, cix_node, ilk='namespace')
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/parser_cix.py", line 178, in common_module_class_cix
    visit_children_get_cix(parse_tree_node, class_cix_node)
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/parser_cix.py", line 215, in visit_children_get_cix
    cb_etree_hash[c.class_name](c, cix_node)
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/parser_cix.py", line 206, in module_etree_cix
    common_module_class_cix(parse_tree_node, cix_node, ilk='namespace')
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/parser_cix.py", line 178, in common_module_class_cix
    visit_children_get_cix(parse_tree_node, class_cix_node)
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/parser_cix.py", line 215, in visit_children_get_cix
    cb_etree_hash[c.class_name](c, cix_node)
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/parser_cix.py", line 189, in class_etree_cix
    common_module_class_cix(parse_tree_node, cix_node, classref_etree_cix)
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/parser_cix.py", line 175, in common_module_class_cix
    get_vars_cix(parse_tree_node, class_cix_node)
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/parser_cix.py", line 162, in get_vars_cix
    "__instancevar__ __local__")
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/parser_cix.py", line 143, in _get_vars_helper
    kind_name, {})):
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/parser_cix.py", line 78, in sort_by_lines
    intermed.sort()
TypeError: unorderable types: str() < NoneType()
unexpected error scanning `base_formatter.rb'
Traceback (most recent call last):
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/citadel.py", line 226, in blob_from_lang
    self._load_buf_data_once()
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/citadel.py", line 166, in _load_buf_data_once
    self._blob_from_lang_cache = self.mgr.db.get_buf_data(self)
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/database/database.py", line 1067, in get_buf_data
    return self._get_lang_zone(buf.lang).get_buf_data(buf)
  File "/Users/audioj/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel3/libs/codeintel2/database/langlib.py", line 831, in get_buf_data
    % (buf.lang, buf.path))
codeintel2.common.NotFoundInDatabase: Ruby buffer '/Users/audioj/.rvm/gems/ruby-2.1.2-railsexpress/gems/rspec-core-2.14.8/lib/rspec/core/formatters/base_formatter.rb' not found in database

During handling of the above exception, another exception occurred:
```

Its happening for each of my gems in my dir

**Comment by wizza-smile** [comment]
I have also experienced this when messing with the db. It always helped to close sublime, delete the codeintel_database folder (the one surrounding the "db" folder), and do a fresh re-indexing!

**Comment by jtoliver** [comment]
```
{
	"folders":
	[
		{
			"path": "/Users/aioj/Sites/nogi"
		}
	],
  "codeintel_settings":
  {
    "codeintel_language_settings":
    {
      "Ruby": {
          "ruby": "/Users/aioj/.rvm/rubies/ruby-2.1.2-railsexpress/bin/ruby",
          "codeintel_word_completions": "all",
          "codeintel_scan_extra_dir": [
            "/Users/aioj/.rvm/gems/ruby-2.1.2-railsexpress/gems",
            "/Users/aioj/.rvm/gems/ruby-2.1.2-railsexpress/bin",
            "/Users/aioj/.rvm/gems/ruby-2.1.2-railsexpress/extensions",
            "/Users/aioj/Sites/nogi"
          ]
      }
    }
  }
}
```

Here is my config

**Comment by wizza-smile** [comment]
Your *.sublime-project file is lookin fine! All settings you don't use here will be taken from your user *.sublime-settings file (and eventually from default settings delivered with plugin). 

So after deleting db , you still get the same errors?

**Comment by jtoliver** [comment]
Its looking better. I'm not seeing the errors anymore.
